name: stow_plain
description: A Stow package to store plaintext data in shared preferences.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ^3.0.0

dependencies:
  shared_preferences: ^2.5.3
  stow: ^1.0.0
  stow_codecs: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
