name: stow_plain
description: A Stow package to store plaintext data in shared preferences.
version: 0.1.2
resolution: workspace
repository: https://github.com/adil192/stow

topics:
  - stow
  - storage
  - shared-preferences
  - persistence

environment:
  sdk: ^3.8.0
  flutter: '>=3.27.0'

dependencies:
  shared_preferences: ^2.5.3
  stow: ^0.1.2
  stow_codecs: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
