name: stow_project
repository: https://github.com/adil192/stow
publish_to: none
environment:
  sdk: ^3.8.0
workspace:
  - packages/stow
  - packages/stow_codecs
  - packages/stow_plain
dev_dependencies:
  melos: ^7.0.0-dev.9
