name: stow_project
repository: https://github.com/adil192/stow
publish_to: none
environment:
  sdk: ^3.8.0
workspace:
  - packages/stow
  - packages/stow_codecs
  - packages/stow_plain
  - packages/stow_secure
dev_dependencies:
  melos: ^7.1.0

melos:
  scripts:
    test:single:
      run: melos exec --dir-exists="test" -- flutter test --no-pub --coverage
      description: Run Flutter tests for a specific package in this project.
      packageFilters:
        dirExists:
          - test
    test:
      run: melos run test:single --no-select
      description: Run Flutter tests for all packages in this project.
