name: stow
description: An abstraction to allow synchronous access to persistent data.
version: 0.5.1+1
resolution: workspace
repository: https://github.com/adil192/stow

topics:
  - stow
  - storage
  - persistence

environment:
  sdk: ^3.8.0
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.16.0
  mutex: ^3.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  stow_codecs: ^1.2.0
