name: stow_secure
description: A Stow package to store encrypted data in flutter_secure_storage.
version: 0.3.0
resolution: workspace
repository: https://github.com/adil192/stow

topics:
  - stow
  - storage
  - flutter-secure-storage
  - persistence
  - encryption

environment:
  sdk: ^3.8.0
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ">=9.0.0 <11.0.0"
  stow: ^0.3.0
  stow_codecs: ^1.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
